### PR TITLE
Fix ListView Overscroll Glow Color

### LINKED ISSUE #209: Fix scroll glow color on `ForecastWidget`

### PR DESCRIPTION
**Pull request by prestosole**
fixes #209

The color of the overscroll glow effect is now defined in the ThemeData.colorScheme.secondary property ([docs](https://api.flutter.dev/flutter/widgets/GlowingOverscrollIndicator-class.html)) as of Flutter 2.2

### CODE REVIEW

File: packages/clima_ui/lib/themes/black_theme.dart [hunk 1]
```diff
@@ -12,6 +12,7 @@ ThemeData blackTheme = ThemeData.dark().copyWith(
   dialogBackgroundColor: const Color(0xFF202125),
   toggleableActiveColor: const Color(0xFF89B4F8),
   accentColor: const Color(0xFF89B4F8),
+  colorScheme: ColorScheme.fromSwatch(accentColor: const Color(0xFF89B4F8)),
```
Comment (triallax) [inline packages/clima_ui/lib/themes/black_theme.dart:15]: Is the `accentColor` thing above this line necessary anymore after adding this?

Also, see https://api.flutter.dev/flutter/material/ThemeData/colorScheme.html:
> New components can be defined exclusively in terms of colorScheme. Existing components will gradually migrate to it, to the extent that is possible without significant backwards compatibility breaks.

We can think later about removing as much of the specific properties as possible in favor of `colorScheme` if it doesn't result in worse colors.

Comment (prestosole) [reply packages/clima_ui/lib/themes/black_theme.dart:15]: I am not sure honestly

Comment (prestosole) [reply packages/clima_ui/lib/themes/black_theme.dart:15]: We can decide on this later I guess

**Review by triallax — APPROVED** [review]
